// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gpt

import (
	"ale-chatGPT/environment"
	"ale-chatGPT/internal/common"
	"ale-chatGPT/internal/usecase"
	"context"
)

// Injectors from wire.go:

func Initialize(ctx context.Context, path string) (App, error) {
	config, err := environment.New(path)
	if err != nil {
		return App{}, err
	}
	gpt := common.NewGPTClient(config)
	infUsecase := usecase.NewGPTUsecase(gpt)
	app := App{
		Config:    config,
		GPTClient: gpt,
		Usecase:   infUsecase,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config    environment.Config
	GPTClient *common.GPT
	Usecase   usecase.InfUsecase
}
